######################################################################
##
## Filename: BinToBCD.udo
## Created on: Wed Mar 25 3:12:24 PM Malay Peninsula Standard Time 2020
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
