######################################################################
##
## Filename: RS232Txd.udo
## Created on: Wed Mar 25 11:04:48 AM Malay Peninsula Standard Time 2020
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
