######################################################################
##
## Filename: tb_LCD.udo
## Created on: Sat Feb 22 5:27:38 PM Malay Peninsula Standard Time 2020
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
