######################################################################
##
## Filename: tb_RS232Txd.udo
## Created on: Wed Feb 26 10:41:23 AM Malay Peninsula Standard Time 2020
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
