######################################################################
##
## Filename: tb_RAMTest.udo
## Created on: Tue Feb 18 7:38:24 PM Malay Peninsula Standard Time 2020
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
