######################################################################
##
## Filename: tb_SPI.udo
## Created on: Wed Feb 19 3:10:11 PM Malay Peninsula Standard Time 2020
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
